name: EDUCATIONALVPS

on:
  workflow_dispatch:

jobs:
  build:
    name: Building Educational VPS
    runs-on: windows-latest
    timeout-minutes: 360
    
    steps:
      - name: DEPLOYING
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/raposabrty/pcrdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: DONE
        run: cmd /c show.bat

      - name: Time Counter
        run: cmd /c loop.bat
